/* Signal & Shelf philosophy: editorial data journalism, warm paper, ink navy, coral for horizontal platforms, teal for verticals, and saffron as the evidence signal. */
import { useMemo, useState } from "react";
import { Download, ExternalLink, Filter, Search, Sparkles } from "lucide-react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import platforms from "@/data/platforms.json";
import summary from "@/data/summary.json";

type Platform = typeof platforms[number];
const COLORS = { Horizontal: "#E46D55", Vertical: "#1D8C86" };

function downloadCsv(rows: Platform[]) {
  const headers = Object.keys(rows[0]);
  const csv = [headers.join(","), ...rows.map((row) => headers.map((h) => `"${String(row[h as keyof Platform]).replaceAll('"', '""')}"`).join(","))].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = "greentern-india-ecommerce-platforms.csv"; a.click(); URL.revokeObjectURL(url);
}

export default function Home() {
  const [type, setType] = useState<"All" | "Horizontal" | "Vertical">("All");
  const [category, setCategory] = useState("All categories");
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<keyof Platform>("platform");

  const categories = useMemo(() => ["All categories", ...Array.from(new Set(platforms.map((p) => p.category))).sort()], []);
  const filtered = useMemo(() => platforms.filter((p) => (type === "All" || p.type === type) && (category === "All categories" || p.category === category) && p.platform.toLowerCase().includes(query.toLowerCase())).sort((a,b) => String(a[sort]).localeCompare(String(b[sort]))), [type, category, query, sort]);
  const categoryChart = Object.entries(summary.category_counts).sort((a,b) => b[1]-a[1]).map(([name, value]) => ({ name: name.replace(" / quick commerce", " / q-commerce"), value }));
  const splitChart = [{ name: "Horizontal", value: summary.horizontal }, { name: "Vertical", value: summary.vertical }];

  return <div className="min-h-screen bg-[#F6F0E6] text-[#1E2A3A]">
    <header className="relative overflow-hidden border-b border-[#1E2A3A]/10 bg-[#F6F0E6]">
      <div className="absolute inset-0 bg-[url('/manus-storage/signal-shelf-texture_2f56a6c7.png')] opacity-40" />
      <div className="relative mx-auto max-w-[1400px] px-5 py-5 lg:px-10">
        <div className="flex items-center justify-between gap-5">
          <div className="flex items-center gap-3"><img src="/manus-storage/signal-shelf-logo_18cb946d.png" className="h-11 w-11 object-contain" alt="Signal & Shelf mark" /><div><div className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#E9943A]">GREENTERN / FIELD NOTE 01</div><div className="font-serif text-lg font-semibold">Signal & Shelf</div></div></div>
          <Button onClick={() => downloadCsv(filtered)} className="gap-2 rounded-full bg-[#1E2A3A] px-4 text-[#F6F0E6] hover:bg-[#E9943A] hover:text-[#1E2A3A]"><Download size={15} /> Download CSV</Button>
        </div>
        <div className="grid gap-8 pb-12 pt-16 lg:grid-cols-[0.95fr_1.4fr] lg:items-end lg:pt-24">
          <div><div className="mb-5 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.24em] text-[#1D8C86]"><Sparkles size={14} /> India e-commerce / 2026 working dataset</div><h1 className="max-w-3xl font-serif text-5xl font-semibold leading-[0.95] tracking-[-0.04em] sm:text-7xl">Scale is visible.<br /><span className="text-[#E46D55]">Disclosure is not.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-[#1E2A3A]/70">A source-first comparison of 30 platforms operating in India, split between horizontal marketplaces and vertical specialists.</p></div>
          <div className="relative hidden min-h-[240px] overflow-hidden rounded-[2rem] border border-[#1E2A3A]/10 bg-[#DDE7E1] lg:block"><img src="/manus-storage/signal-shelf-hero_de880fa3.png" className="absolute inset-0 h-full w-full object-cover mix-blend-multiply opacity-80" alt="Abstract market map illustration" /><div className="absolute bottom-5 left-5 max-w-[250px] rounded-xl bg-[#F6F0E6]/90 p-4 backdrop-blur"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#E9943A]">Research cue</div><div className="mt-1 font-serif text-xl font-semibold leading-tight">Trace the category mix before you call it a market.</div></div></div>
        </div>
      </div>
    </header>

    <main className="mx-auto max-w-[1400px] px-5 py-8 lg:px-10 lg:py-12">
      <section className="mb-8 overflow-hidden rounded-2xl border border-[#1E2A3A]/10 bg-[#FFFDF8] shadow-[0_12px_35px_rgba(30,42,58,0.06)]"><div className="grid grid-cols-2"><div className="relative bg-[#E46D55] px-5 py-4 text-white lg:px-7"><div className="absolute right-0 top-0 h-full w-px bg-[#F6F0E6]/40" /><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-white/75">Horizontal / breadth</div><div className="mt-2 flex items-end justify-between gap-4"><span className="font-serif text-4xl font-semibold">{summary.horizontal}</span><span className="pb-1 text-right text-xs text-white/75">general, value,<br />network &amp; B2B</span></div></div><div className="bg-[#1D8C86] px-5 py-4 text-white lg:px-7"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-white/75">Vertical / depth</div><div className="mt-2 flex items-end justify-between gap-4"><span className="font-serif text-4xl font-semibold">{summary.vertical}</span><span className="pb-1 text-right text-xs text-white/75">fashion, beauty,<br />grocery &amp; more</span></div></div></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#1E2A3A]/10 px-5 py-3 text-xs text-[#1E2A3A]/60 lg:px-7"><span><strong className="text-[#1E2A3A]">Signature split:</strong> two operating logics, one market map.</span><span className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#E9943A]">Analyst annotation · sample design</span></div></section>
      <section className="grid gap-4 md:grid-cols-4">
        {[{label:"Platforms mapped", value:summary.total, note:"30-row working set"},{label:"Horizontal", value:summary.horizontal, note:"breadth + aggregation", color:"#E46D55"},{label:"Vertical / specialty", value:summary.vertical, note:"category depth", color:"#1D8C86"},{label:"Explicit scale figures", value:summary.explicit_scale_disclosures, note:"others remain NPD", color:"#E9943A"}].map((m) => <Card key={m.label} className="border-0 bg-[#FFFDF8] p-5 shadow-[0_12px_35px_rgba(30,42,58,0.06)]"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#1E2A3A]/50">{m.label}</div><div className="mt-3 font-serif text-5xl font-semibold" style={{color:m.color}}>{m.value}</div><div className="mt-2 text-sm text-[#1E2A3A]/55">{m.note}</div><div className="mt-4 border-t border-[#1E2A3A]/10 pt-2 font-mono text-[9px] uppercase tracking-[0.14em] text-[#1E2A3A]/40">Dataset snapshot · 18 Aug 2026</div></Card>)}
      </section>

      <section className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]">
        <Card className="border-0 bg-[#FFFDF8] p-5 shadow-[0_12px_35px_rgba(30,42,58,0.06)] lg:p-7"><div className="mb-4 flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#E9943A]">01 / market shape</div><h2 className="mt-2 font-serif text-2xl font-semibold">The split is structural</h2><p className="mt-1 text-sm text-[#1E2A3A]/55">A deliberately mixed sample, not a league table.</p><div className="mt-3 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-[#E9943A]"><span className="h-px w-7 bg-[#E9943A]" />Source: compiled platform set · as-of 18 Aug 2026</div></div><Badge className="rounded-full bg-[#F6F0E6] text-[#1E2A3A]">{summary.total} rows</Badge></div><div className="h-[245px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={splitChart} dataKey="value" nameKey="name" innerRadius={65} outerRadius={96} paddingAngle={4}>{splitChart.map((e) => <Cell key={e.name} fill={COLORS[e.name as keyof typeof COLORS]} />)}</Pie><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e5ddd0',background:'#fffdf8'}} /></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-8 text-sm">{splitChart.map((e) => <div key={e.name} className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:COLORS[e.name as keyof typeof COLORS]}} />{e.name} <strong>{e.value}</strong></div>)}</div></Card>
        <Card className="border-0 bg-[#1E2A3A] p-6 text-[#F6F0E6] shadow-[0_12px_35px_rgba(30,42,58,0.12)] lg:p-7"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#E9943A]">02 / what stands out</div><h2 className="mt-2 font-serif text-3xl font-semibold leading-tight">Owned assortment is a shared playbook.</h2><p className="mt-5 text-sm leading-relaxed text-[#F6F0E6]/70">22 of 30 rows explicitly identify a private or owned label. It appears in both general marketplaces and specialists — from fashion and beauty to grocery, electronics, and D2C brands.</p><div className="mt-8 h-px bg-[#F6F0E6]/15" /><div className="mt-6 grid grid-cols-2 gap-5"><div><div className="font-serif text-4xl font-semibold text-[#E9943A]">{summary.private_label_yes}</div><div className="mt-1 text-xs text-[#F6F0E6]/55">owned-label signals</div></div><div><div className="font-serif text-4xl font-semibold text-[#8DD3C7]">{summary.quick_or_same_day}</div><div className="mt-1 text-xs text-[#F6F0E6]/55">quick / same-day signals</div></div></div></Card>
      </section>

      <section className="mt-8 grid gap-5 lg:grid-cols-[1.05fr_0.95fr]">
        <Card className="border-0 bg-[#FFFDF8] p-5 shadow-[0_12px_35px_rgba(30,42,58,0.06)] lg:p-7"><div className="mb-4"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#1D8C86]">03 / category density</div><h2 className="mt-2 font-serif text-2xl font-semibold">Specialty is not one category</h2><div className="mt-3 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-[#E9943A]"><span className="h-px w-7 bg-[#E9943A]" />Derived from standardized Category field · n=30</div></div><div className="h-[330px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={categoryChart} layout="vertical" margin={{left:6,right:20,top:5,bottom:5}}><XAxis type="number" allowDecimals={false} hide /><YAxis dataKey="name" type="category" width={160} tick={{fontSize:11,fill:'#1E2A3A'}} /><Tooltip cursor={{fill:'#F6F0E6'}} contentStyle={{borderRadius:12,border:'1px solid #e5ddd0',background:'#fffdf8'}} /><Bar dataKey="value" fill="#1D8C86" radius={[0,6,6,0]} /></BarChart></ResponsiveContainer></div></Card>
        <Card className="border-0 bg-[#E9EFE9] p-6 shadow-[0_12px_35px_rgba(30,42,58,0.06)] lg:p-7"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-[#E46D55]"><span className="h-px w-7 bg-[#E9943A]" />Method note</div><h2 className="mt-2 font-serif text-2xl font-semibold">NPD is a finding, not a blank to fill.</h2><p className="mt-4 text-sm leading-relaxed text-[#1E2A3A]/70">Only {summary.explicit_scale_disclosures} rows carry an explicit scale figure in this first pass. Because MAU, GMV, revenue, and orders are not reported consistently, this dashboard does not manufacture a single ranking metric. Each row keeps its source URL and as-of note.</p><a className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#1D8C86] underline decoration-[#1D8C86]/30 underline-offset-4" href="https://www.bain.com/insights/how-india-shops-online-2025/" target="_blank" rel="noreferrer">Read market context <ExternalLink size={14} /></a></Card>
      </section>

      <section className="mt-12" id="dataset"><div className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#E9943A]">04 / inspect the rows</div><h2 className="mt-2 font-serif text-3xl font-semibold">The working dataset</h2><p className="mt-1 text-sm text-[#1E2A3A]/55">Search, filter, and open the source trail. Unknowns stay visible.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setType("All")} className={type === "All" ? "border-[#1E2A3A] bg-[#1E2A3A] text-[#F6F0E6]" : "border-[#1E2A3A]/15 bg-transparent"}>All</Button><Button variant="outline" onClick={() => setType("Horizontal")} className={type === "Horizontal" ? "border-[#E46D55] bg-[#E46D55] text-white" : "border-[#1E2A3A]/15 bg-transparent"}>Horizontal</Button><Button variant="outline" onClick={() => setType("Vertical")} className={type === "Vertical" ? "border-[#1D8C86] bg-[#1D8C86] text-white" : "border-[#1E2A3A]/15 bg-transparent"}>Vertical</Button></div></div>
        <div className="mb-4 grid gap-3 md:grid-cols-[1fr_260px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[#1E2A3A]/40" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search platform name" className="border-[#1E2A3A]/15 bg-[#FFFDF8] pl-9" /></div><div className="relative"><Filter className="absolute left-3 top-3 h-4 w-4 text-[#1E2A3A]/40" /><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-10 w-full appearance-none rounded-md border border-[#1E2A3A]/15 bg-[#FFFDF8] pl-9 pr-3 text-sm">{categories.map((c) => <option key={c}>{c}</option>)}</select></div></div>
        <div className="overflow-hidden rounded-2xl border border-[#1E2A3A]/10 bg-[#FFFDF8] shadow-[0_12px_35px_rgba(30,42,58,0.06)]"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-[#1E2A3A] text-[10px] uppercase tracking-[0.14em] text-[#F6F0E6]/70"><tr>{[["platform","Platform"],["type","Type"],["category","Category"],["parent","Ownership"],["scale_metric","Scale metric"],["profitability","Profitability"],["private_label","Private label"],["quick_delivery","Delivery"],["source","Evidence"]].map(([key,label]) => <th key={key} onClick={() => setSort(key as keyof Platform)} className="cursor-pointer px-4 py-3 font-mono hover:text-white">{label}</th>)}</tr></thead><tbody>{filtered.map((p) => <tr key={p.platform} className="border-b border-[#1E2A3A]/8 last:border-0 hover:bg-[#F6F0E6]/70"><td className="px-4 py-4 font-semibold">{p.platform}</td><td className="px-4 py-4"><span className="rounded-full px-2 py-1 text-[11px] font-semibold" style={{background: p.type === "Horizontal" ? "#FBE4DE" : "#DCEFEB", color: p.type === "Horizontal" ? "#A84836" : "#17645F"}}>{p.type}</span></td><td className="px-4 py-4 text-[#1E2A3A]/65">{p.category}</td><td className="max-w-[190px] px-4 py-4 text-[#1E2A3A]/65">{p.parent}</td><td className="max-w-[230px] px-4 py-4 text-[#1E2A3A]/65">{p.scale_metric}</td><td className="px-4 py-4 text-[#1E2A3A]/65">{p.profitability}</td><td className="max-w-[220px] px-4 py-4 text-[#1E2A3A]/65">{p.private_label}</td><td className="max-w-[220px] px-4 py-4 text-[#1E2A3A]/65">{p.quick_delivery}</td><td className="px-4 py-4"><a href={p.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[#1D8C86] underline decoration-[#1D8C86]/30 underline-offset-4">{p.source} <ExternalLink size={13} /></a></td></tr>)}</tbody></table></div><div className="border-t border-[#1E2A3A]/10 px-4 py-3 text-xs text-[#1E2A3A]/50">Showing {filtered.length} of {platforms.length} platforms · NPD = not publicly disclosed in the reviewed source set</div></div>
      </section>
    </main>
    <footer className="mx-auto max-w-[1400px] border-t border-[#1E2A3A]/10 px-5 py-8 text-xs text-[#1E2A3A]/55 lg:px-10"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><strong className="text-[#1E2A3A]">Greentern assignment / India e-commerce research</strong><br />Compiled as a transparent working dataset; validate figures against the latest filings before submission.</div><div className="font-mono uppercase tracking-[0.16em]">Signal & Shelf · 18 Aug 2026</div></div></footer>
  </div>;
}
